env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  max-len:
    - warn
    - 80
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - warn
  react/prop-types:
    - error
    - skipUndeclared: true
  no-unused-vars:
    - error
    - varsIgnorePattern: ^_$
